### ISSUE TITLE
Damage suggestion

### ISSUE THREAD

**Issue by Bunsan** [JAWolfe04/TerrafirmaPunk-Tweaks#1]
For your calculation done to prevent players from dying of poison I suggest changing to something like
TFC_Core.getEntityMaxHealth(entity)*0.9f; instead of <=0 on line 44 of the PlayerDamageHandler.java.

This rewards players for having high health and balances the fact that TFC health recovers much slower than vanilla. Having a base level player reduced to 100 HP seems fair.

**Comment by StrayWolfe** [comment]
Thanks for the suggestion. It has been implemented and will be added in the next update.
